---
- name: Testing facts
  hosts: servera.lab.example.com
  gather_facts: false
  tasks:
    - name: list facts for servera and serverb
      debug:
        msg:
          - "Value of value1 in: "
          - "    servera: {{ hostvars['servera.lab.example.com'].value1 | default('Undefined')" 
          - "    serverb: {{ hostvars['serverb.lab.example.com'].value1 | default('Undefined')" 

    - name: Creating fact
      set_fact:
        value1: 123

    - name: list facts for servera and serverb
      debug:
        msg:
          - "Value of value1 in: "
          - "    servera: {{ hostvars['servera.lab.example.com'].value1 | default('Undefined')" 
          - "    serverb: {{ hostvars['serverb.lab.example.com'].value1 | default('Undefined')" 
